version: '3'
services:

  spring-boot-app:
    container_name: docker-postgres-springboot-demo-app
    environment:
      - POSTGRES_HOST=docker-postgres-db
    ports:
      - "8082:8082"
    build: ./user-service/
    restart: on-failure

  postgresDb:
    image: postgres:13.2
    container_name: docker-postgres-db
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=spring_boot_postgres_db

  elastic-search:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200

  logstash:
    image: logstash:7.14.1
    container_name: logstash
    restart: always
    ports:
      - "5001:5003"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true