server:
  port: 8084

spring:
  data:
    mongodb:
      host: ${HOST_NAME:localhost}
      port: 27017
      database: mongo
      password: bdung
      username: mongoadmin
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true